connections {
    n3-urllc-cu-edge {
        local_addrs = 10.97.0.11
        remote_addrs = 10.97.0.12
        proposals = aes128gcm16-prfsha256-mlkem768
        ppk_id = ppk-urllc-qkd
        ppk_required = yes
        local { auth = psk }
        remote { auth = psk }
        children {
            n3-urllc-cu-edge {
                local_ts = 172.18.0.99/32
                remote_ts = 172.18.0.0/16
                esp_proposals = aes128gcm16-mlkem768
                mode = tunnel
                mark_in = 0x10
                mark_out = 0x10
                start_action = none
            }
        }
        version = 2
    }
    n3-embb-cu-edge {
        local_addrs = 10.97.0.21
        remote_addrs = 10.97.0.22
        proposals = aes256gcm16-prfsha256-mlkem512
        local { auth = psk }
        remote { auth = psk }
        children {
            n3-embb-cu-edge {
                local_ts = 172.18.0.99/32
                remote_ts = 172.18.0.0/16
                esp_proposals = aes256gcm16-mlkem512
                mode = tunnel
                mark_in = 0x20
                mark_out = 0x20
                start_action = none
            }
        }
        version = 2
    }
    n3-miot-cu-edge {
        local_addrs = 10.97.0.31
        remote_addrs = 10.97.0.32
        proposals = aes128gcm16-prfsha256-mlkem512
        local { auth = psk }
        remote { auth = psk }
        children {
            n3-miot-cu-edge {
                local_ts = 172.18.0.99/32
                remote_ts = 172.18.0.0/16
                esp_proposals = aes128gcm16-mlkem512
                mode = tunnel
                mark_in = 0x30
                mark_out = 0x30
                start_action = none
            }
        }
        version = 2
    }
}
